import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

export interface SignerCert {
  index: number; total: number;
  name: string; email: string; phone: string | null;
  signedAt: Date; signedIp: string; userAgent: string;
  emailVerifiedAt: Date; smsVerifiedAt: Date | null;
  consentText: string; signTokenHash: string;
}
export interface CertInput {
  documentId: string;
  documentSha256: string;
  originalFilename: string;
  originalFormat: "pdf" | "markdown" | "text";
  createdAt: Date;
  senderEmail: string;
  senderIp: string;
  senderConfirmedAt: Date;
  signers: SignerCert[];
  appVersion: string;
  generatedAt: Date;
}

export async function buildAuditAppendix(cert: CertInput): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const mono = await pdf.embedFont(StandardFonts.Courier);
  let page = pdf.addPage([595.28, 841.89]); // A4
  let y = 800;
  const draw = (text: string, opts: { size?: number; bold?: boolean; code?: boolean } = {}) => {
    const size = opts.size ?? 10;
    if (y < 60) { page = pdf.addPage([595.28, 841.89]); y = 800; }
    page.drawText(text, { x: 50, y, size, font: opts.bold ? fontBold : opts.code ? mono : font, color: rgb(0,0,0) });
    y -= size + 4;
  };
  draw("SIGNATURE CERTIFICATE", { size: 16, bold: true });
  y -= 6;
  draw(`Document ID:       ${cert.documentId}`, { code: true });
  draw(`Document SHA-256:  ${cert.documentSha256}`, { code: true });
  draw(`Original filename: ${cert.originalFilename}`);
  draw(`Original format:   ${cert.originalFormat}`);
  draw(`Created:           ${cert.createdAt.toISOString()} by ${cert.senderEmail} (IP ${cert.senderIp})`);
  draw(`Sender confirmed:  ${cert.senderConfirmedAt.toISOString()}`);
  y -= 6;
  for (const s of cert.signers) {
    draw(`Signer ${s.index} of ${s.total}: ${s.name} <${s.email}>`, { bold: true });
    draw(`  Signed:          ${s.signedAt.toISOString()} from IP ${s.signedIp}`);
    draw(`  Email verified:  ${s.emailVerifiedAt.toISOString()} (clicked unique token)`);
    draw(`  SMS verified:    ${s.smsVerifiedAt ? `${s.smsVerifiedAt.toISOString()} on ${s.phone}` : "not required"}`);
    draw(`  User agent:      ${s.userAgent.slice(0, 100)}`);
    draw(`  Consent text:    "${s.consentText}"`);
    draw(`  Sign-token hash: ${s.signTokenHash}`, { code: true });
    y -= 6;
  }
  draw(`Generated by esign.newcommerce.no v${cert.appVersion} at ${cert.generatedAt.toISOString()}`, { size: 8 });
  return await pdf.save();
}
